=== YONEDASH/DHBW_MW/XML/portfolio.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="KategorieType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sportscar"/>
            <xs:enumeration value="Hypercar"/>
            <xs:enumeration value="Luxus"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GewichtseinheitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="kg"/>
            <xs:enumeration value="t"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PowereinheitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hp"/>
            <xs:enumeration value="kwh"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PreiseinheitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Euro"/>
            <xs:enumeration value="Dollar"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="KraftstoffType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Diesel"/>
            <xs:enumeration value="Benzin"/>
            <xs:enumeration value="Strom"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FahrwerkType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="FWD"/>
            <xs:enumeration value="RWD"/>
            <xs:enumeration value="AWD"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SchaltungType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Automatik"/>
            <xs:enumeration value="Manuell"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AutoIdType">
        <xs:restriction base="xs:string">
            <xs:length value="7" />
            <xs:pattern value="[a-zA-Z]-[a-zA-Z0-9]{5}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AutoIdentifier">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Auto" maxOccurs="unbounded" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation> Verwendungzweck: Datenbasis f√ºr Autos, um in Onlinekatalog angezeigt zu werden. </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="AutoIdentifier" name="Marke"/>
                            <xs:element type="AutoIdentifier" name="Name"/>
                            <xs:element type="KategorieType" name="Kategorie"/>
                            <xs:element type="xs:short" name="Erscheinungsjahr"/>
                            <xs:element name="Gewicht">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:short" name="Gewichtswert"/>
                                        <xs:element type="GewichtseinheitType" name="Gewichtseinheit"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Preis">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:int" name="Preiswert"/>
                                        <xs:element type="PreiseinheitType" name="Preiseinheit"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Motoren">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Motor" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Power">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:short" name="Powerwert"/>
                                                                <xs:element type="xs:string" name="Powereinheit"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element type="xs:string" name="Bezeichnung" minOccurs="0"/>
                                                    <xs:element type="KraftstoffType" name="Kraftstoff"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Fahrwerk">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="FahrwerkType" name="typ" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Schaltung">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="Gaenge"/>
                                        <xs:element type="SchaltungType" name="Art"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="AutoIdType" name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YONEDASH/DHBW_MW/XML/autohaus.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./portfolio.xsd">
    <Auto id="P-2G3RS">
        <Marke>Porsche</Marke>
        <Name>911 GT3 R rennsport (992)</Name>
        <Kategorie>Sportscar</Kategorie>
        <Erscheinungsjahr>2023</Erscheinungsjahr>
        <Gewicht>
            <Gewichtswert>1240</Gewichtswert>
            <Gewichtseinheit>kg</Gewichtseinheit>
        </Gewicht>
        <Preis>
            <Preiswert>951000</Preiswert>
            <Preiseinheit>Euro</Preiseinheit>
        </Preis>
        <Motoren>
            <Motor>
                <Power>
                    <Powerwert>629</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Bezeichnung>Boxer Motor</Bezeichnung>
                <Kraftstoff>Benzin</Kraftstoff>
            </Motor>
        </Motoren>
        <Fahrwerk>
            <Typ>RWD</Typ>
        </Fahrwerk>
        <Schaltung>
            <Gaenge>6</Gaenge>
            <Art>Manuell</Art>
        </Schaltung>
    </Auto>
    <Auto id="M-RX7FD">
        <Marke>Mazda</Marke>
        <Name>RX-7</Name>
        <Kategorie>Sportscar</Kategorie>
        <Erscheinungsjahr>1997</Erscheinungsjahr>
        <Gewicht>
            <Gewichtswert>1325</Gewichtswert>
            <Gewichtseinheit>kg</Gewichtseinheit>
        </Gewicht>
        <Preis>
            <Preiswert>34000</Preiswert>
            <Preiseinheit>Euro</Preiseinheit>
        </Preis>
        <Motoren>
            <Motor>
                <Power>
                    <Powerwert>239</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Bezeichnung>Wankelmoor mit zwei Rotoren</Bezeichnung>
                <Kraftstoff>Benzin</Kraftstoff>
            </Motor>
        </Motoren>
        <Fahrwerk>
            <Typ>RWD</Typ>
        </Fahrwerk>
        <Schaltung>
            <Gaenge>5</Gaenge>
            <Art>Manuell</Art>
        </Schaltung>
    </Auto>
    <Auto id="L-P1M15">
        <Marke>McLaren</Marke>
        <Name>P1</Name>
        <Kategorie>Hypercar</Kategorie>
        <Erscheinungsjahr>2015</Erscheinungsjahr>
        <Gewicht>
            <Gewichtswert>1490</Gewichtswert>
            <Gewichtseinheit>kg</Gewichtseinheit>
        </Gewicht>
        <Preis>
            <Preiswert>1350000</Preiswert>
            <Preiseinheit>Euro</Preiseinheit>
        </Preis>
        <Motoren>
            <Motor>
                <Power>
                    <Powerwert>726</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Bezeichnung>V8 SSG</Bezeichnung>
                <Kraftstoff>Benzin</Kraftstoff>
            </Motor>
            <Motor>
                <Power>
                    <Powerwert>177</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Kraftstoff>Strom</Kraftstoff>
            </Motor>
        </Motoren>
        <Fahrwerk>
            <Typ>RWD</Typ>
        </Fahrwerk>
        <Schaltung>
            <Gaenge>7</Gaenge>
            <Art>Automatik</Art>
        </Schaltung>
    </Auto>
    <Auto id="K-JSK21">
        <Marke>Koenigsegg</Marke>
        <Name>Jesko</Name>
        <Kategorie>Hypercar</Kategorie>
        <Erscheinungsjahr>2021</Erscheinungsjahr>
        <Gewicht>
            <Gewichtswert>1420</Gewichtswert>
            <Gewichtseinheit>kg</Gewichtseinheit>
        </Gewicht>
        <Preis>
            <Preiswert>3000000</Preiswert>
            <Preiseinheit>Euro</Preiseinheit>
        </Preis>
        <Motoren>
            <Motor>
                <Power>
                    <Powerwert>1281</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Bezeichnung>twin-turbo charged V8</Bezeichnung>
                <Kraftstoff>Benzin</Kraftstoff>
            </Motor>
        </Motoren>
        <Fahrwerk>
            <Typ>RWD</Typ>
        </Fahrwerk>
        <Schaltung>
            <Gaenge>9</Gaenge>
            <Art>Automatik</Art>
        </Schaltung>
    </Auto>
    <Auto id="B-CGT21">
        <Marke>Bentley</Marke>
        <Name>Continental GT Speed</Name>
        <Kategorie>Luxus</Kategorie>
        <Erscheinungsjahr>2021</Erscheinungsjahr>
        <Gewicht>
            <Gewichtswert>2273</Gewichtswert>
            <Gewichtseinheit>kg</Gewichtseinheit>
        </Gewicht>
        <Preis>
            <Preiswert>380000</Preiswert>
            <Preiseinheit>Euro</Preiseinheit>
        </Preis>
        <Motoren>
            <Motor>
                <Power>
                    <Powerwert>650</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Bezeichnung>W12</Bezeichnung>
                <Kraftstoff>Benzin</Kraftstoff>
            </Motor>
        </Motoren>
        <Fahrwerk>
            <Typ>AWD</Typ>
        </Fahrwerk>
        <Schaltung>
            <Gaenge>8</Gaenge>
            <Art>Automatik</Art>
        </Schaltung>
    </Auto>
    <Auto id="R-PHTM7">
        <Marke>Rolls Royce</Marke>
        <Name>Phantom VIII</Name>
        <Kategorie>Luxus</Kategorie>
        <Erscheinungsjahr>2018</Erscheinungsjahr>
        <Gewicht>
            <Gewichtswert>2610</Gewichtswert>
            <Gewichtseinheit>kg</Gewichtseinheit>
        </Gewicht>
        <Preis>
            <Preiswert>570000</Preiswert>
            <Preiseinheit>Euro</Preiseinheit>
        </Preis>
        <Motoren>
            <Motor>
                <Power>
                    <Powerwert>563</Powerwert>
                    <Powereinheit>hp</Powereinheit>
                </Power>
                <Bezeichnung>N74B68</Bezeichnung>
                <Kraftstoff>Benzin</Kraftstoff>
            </Motor>
        </Motoren>
        <Fahrwerk>
            <Typ>RWD</Typ>
        </Fahrwerk>
        <Schaltung>
            <Gaenge>8</Gaenge>
            <Art>Automatik</Art>
        </Schaltung>
    </Auto>
</Portfolio>
